spring:
  datasource:
    url: jdbc:postgresql://jobsearcher.cxpw7yqm10wu.sa-east-1.rds.amazonaws.com/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181

  spring:
