spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobsearch
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8181